-- =============================================================================
-- Streetwise Self Defense: Airtable → Supabase (Phase 1 — like-for-like schema)
-- =============================================================================
-- Tables mirror the 12 Airtable tables one-to-one. Airtable record IDs are
-- preserved in `airtable_record_id` so the Phase 2 data migration can resolve
-- linked-record references to Supabase UUID foreign keys.
--
-- Not included (intentional, for the reasons below):
--   • Lookup fields (e.g. Bookings."Class (from Class Schedule)",
--     Participants."Contact Email (from Booking)") — derive via JOIN.
--   • Formula fields (e.g. Class Schedules."Remaining Spots") — compute in
--     queries or add a view in Phase 3.
--   • Rollup fields (e.g. Class Schedules."Booked Spots") — same.
--   • Airtable "Created time" / "Last modified time" formula fields — replaced
--     by standard `created_at` / `updated_at` columns on every table.
-- =============================================================================

create extension if not exists pgcrypto;

create or replace function set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;


-- =============================================================================
-- 1. classes  (Airtable: Classes)
-- =============================================================================
create table classes (
  id uuid primary key default gen_random_uuid(),
  airtable_record_id text unique,

  class_id text,                              -- Airtable "ID" (single line text, primary field)
  class_name text not null,
  description text,
  type text check (type in (
    'Public: Adult & Teen',
    'Public: Mother & Daughter',
    'Private',
    'Corporate',
    'Community: Mother & Daughter'
  )),
  age_range text,
  duration integer,
  max_participants integer,
  location text,
  instructor text,
  price integer,
  booking_method text check (booking_method in (
    'External', 'Contact', 'SWSD website', 'Streetwise Self Defense'
  )),
  registration_instructions text,
  is_active boolean not null default false,
  partner_organization text check (partner_organization in (
    'City of Walnut Creek -- Arts & Recreation',
    'Diablo Valley College',
    'Streetwise Self Defense'
  )),
  city text check (city in (
    'Walnut Creek', 'Pleasant Hill', 'Richmond', 'San Francisco', 'San Jose'
  )),
  parking_instructions text,
  parking_map_url text,
  pricing_unit text check (pricing_unit in (
    'Per Person', 'Per Mother/Daughter Pair'
  )),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger classes_updated_at before update on classes
  for each row execute function set_updated_at();
create index classes_is_active_idx on classes (is_active);
create index classes_type_idx on classes (type);


-- =============================================================================
-- 2. class_schedules  (Airtable: Class Schedules)
-- =============================================================================
create table class_schedules (
  id uuid primary key default gen_random_uuid(),
  airtable_record_id text unique,

  schedule_id bigint not null generated by default as identity unique,  -- Airtable "Id" autonumber
  class_id uuid references classes(id) on delete restrict,              -- Airtable "Class" linked record
  date date,
  start_time text,                                                      -- e.g. "6:00 PM"
  end_time text,
  start_time_new timestamptz,                                           -- Airtable "Start Time New"
  end_time_new timestamptz,
  is_cancelled boolean not null default false,
  special_notes text,
  description text,
  booking_url text,
  pricing_unit text check (pricing_unit in (
    'Per Person', 'Per Mother/Daughter Pair'
  )),
  registration_opens timestamptz,
  available_spots integer,
  waiver_url text,
  synced_to_zoho boolean not null default false,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger class_schedules_updated_at before update on class_schedules
  for each row execute function set_updated_at();
create index class_schedules_class_id_idx on class_schedules (class_id);
create index class_schedules_date_idx on class_schedules (date);
create index class_schedules_is_cancelled_idx on class_schedules (is_cancelled);


-- =============================================================================
-- 3. bookings  (Airtable: Bookings)
-- =============================================================================
create table bookings (
  id uuid primary key default gen_random_uuid(),
  airtable_record_id text unique,

  booking_id bigint not null generated by default as identity unique,   -- Airtable "Booking ID" autonumber
  class_schedule_id uuid references class_schedules(id) on delete restrict,
  booking_date timestamptz,
  status text check (status in (
    'Pending Payment', 'Confirmed', 'Cancelled', 'Refunded', 'Aborted'
  )),
  contact_first_name text,
  contact_last_name text,
  contact_email text,
  contact_phone text,
  contact_is_participant boolean not null default false,
  number_of_participants integer,
  total_amount numeric(10, 2),

  stripe_payment_intent_id text,
  stripe_checkout_session_id text,
  payment_status text check (payment_status in (
    'Pending', 'Completed', 'Refunded', 'Failed', 'Expired', 'Prepaid'
  )),
  payment_date timestamptz,
  payment_notes text,

  age_validation_status text check (age_validation_status in ('Valid', 'Needs Review')),
  validation_notes text,

  refund_status text check (refund_status in ('None', 'Partial', 'Full')),
  refund_amount numeric(10, 2),
  refund_date timestamptz,
  refund_reason text check (refund_reason in ('Customer Request', 'Class Cancelled', 'Other')),
  refund_notes text,

  participants_json text,
  hold_expires_at timestamptz,
  zoho_synced boolean not null default false,

  -- Confirmation email tracking
  confirmation_email_id text,
  confirmation_email_status text check (confirmation_email_status in (
    'Sent', 'Delivered', 'Delayed', 'Bounced', 'Spam', 'Opened', 'Clicked'
  )),
  confirmation_email_sent_at timestamptz,
  confirmation_email_delivered_at timestamptz,
  confirmation_email_clicked_at timestamptz,

  -- Reminder email tracking
  reminder_email_id text,
  reminder_email_status text check (reminder_email_status in (
    'Sent', 'Delivered', 'Delayed', 'Bounced', 'Spam', 'Opened', 'Clicked'
  )),
  reminder_email_sent_at timestamptz,
  reminder_email_delivered_at timestamptz,
  reminder_email_clicked_at timestamptz,

  -- Followup email tracking (Airtable stores status as single-line text, no enum)
  followup_email_id text,
  followup_email_status text,
  followup_email_sent_at timestamptz,
  followup_email_delivered_at timestamptz,
  followup_email_clicked_at timestamptz,

  email_unsubscribed boolean not null default false,
  email_unsubscribed_at timestamptz,

  -- Reminder SMS tracking
  reminder_sms_id text,
  reminder_sms_status text check (reminder_sms_status in (
    'Sent', 'Delivered', 'Failed', 'Undelivered'
  )),
  reminder_sms_sent_at timestamptz,
  reminder_sms_delivered_at timestamptz,

  -- Preclass SMS tracking
  preclass_sms_id text,
  preclass_sms_status text check (preclass_sms_status in (
    'Sent', 'Delivered', 'Failed', 'Undelivered'
  )),
  preclass_sms_sent_at timestamptz,
  preclass_sms_delivered_at timestamptz,

  sms_unsubscribed boolean not null default false,
  sms_unsubscribed_at timestamptz,
  sms_consent_date timestamptz,
  sms_opted_out_date timestamptz,

  -- Reschedule tracking
  original_participant_count integer,
  offshoot_booking_ids text,
  original_booking_id text,
  reschedule_status text check (reschedule_status in ('Pending Reschedule')),
  reschedule_notes text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger bookings_updated_at before update on bookings
  for each row execute function set_updated_at();
create index bookings_class_schedule_id_idx on bookings (class_schedule_id);
create index bookings_status_idx on bookings (status);
create index bookings_contact_email_idx on bookings (contact_email);
create index bookings_contact_phone_idx on bookings (contact_phone);
create index bookings_stripe_session_id_idx on bookings (stripe_checkout_session_id);
create index bookings_stripe_payment_intent_idx on bookings (stripe_payment_intent_id);
create index bookings_hold_expires_at_idx on bookings (hold_expires_at)
  where status = 'Pending Payment';


-- =============================================================================
-- 4. participants  (Airtable: Participants)
-- =============================================================================
create table participants (
  id uuid primary key default gen_random_uuid(),
  airtable_record_id text unique,

  participant_id bigint not null generated by default as identity unique,
  booking_id uuid references bookings(id) on delete cascade,
  first_name text not null,
  last_name text not null,
  age_group text check (age_group in ('Under 12', '12-15', '16+')),
  participant_number integer,
  special_needs text,
  guardian_name text,
  dietary_requirements text,
  contact_email text,
  emergency_contact_number text,
  attendance text check (attendance in ('Not Recorded', 'Present', 'Absent'))
    not null default 'Not Recorded',
  teaching_assistants text,

  -- Confirmation email tracking
  confirmation_email_id text,
  confirmation_email_status text check (confirmation_email_status in (
    'Sent', 'Delivered', 'Delayed', 'Bounced', 'Spam', 'Opened', 'Clicked'
  )),
  confirmation_email_sent_at timestamptz,
  confirmation_email_delivered_at timestamptz,
  confirmation_email_opened_at timestamptz,

  -- Reminder email tracking
  reminder_email_id text,
  reminder_email_status text check (reminder_email_status in (
    'Sent', 'Delivered', 'Delayed', 'Bounced', 'Spam', 'Opened', 'Clicked'
  )),
  reminder_email_sent_at timestamptz,
  reminder_email_delivered_at timestamptz,
  reminder_email_opened_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger participants_updated_at before update on participants
  for each row execute function set_updated_at();
create index participants_booking_id_idx on participants (booking_id);


-- =============================================================================
-- 5. persons  (Airtable: Persons)
-- =============================================================================
create table persons (
  id uuid primary key default gen_random_uuid(),
  airtable_record_id text unique,

  name text not null,
  email text,
  phone text,
  roles text[],                               -- Airtable multiple select: Student, Parent, Teaching Assistant
  status text check (status in ('Active', 'Inactive')) not null default 'Active',
  notes text,
  emergency_contact_name text,
  emergency_contact_relationship text,
  emergency_contact_phone text,
  emergency_contact_email text,
  source_participant_id uuid references participants(id) on delete set null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger persons_updated_at before update on persons
  for each row execute function set_updated_at();
create index persons_email_idx on persons (email);
create index persons_phone_idx on persons (phone);
create index persons_status_idx on persons (status);
create index persons_roles_idx on persons using gin (roles);


-- =============================================================================
-- 6. teaching_assignments  (Airtable: Teaching Assignments)
-- =============================================================================
create table teaching_assignments (
  id uuid primary key default gen_random_uuid(),
  airtable_record_id text unique,

  assignment_id bigint not null generated by default as identity unique,
  person_id uuid references persons(id) on delete restrict,
  class_schedule_id uuid references class_schedules(id) on delete restrict,
  assignment_notes text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  unique (person_id, class_schedule_id)
);
create trigger teaching_assignments_updated_at before update on teaching_assignments
  for each row execute function set_updated_at();
create index teaching_assignments_person_id_idx on teaching_assignments (person_id);
create index teaching_assignments_class_schedule_id_idx on teaching_assignments (class_schedule_id);


-- =============================================================================
-- 7. testimonials  (Airtable: Testimonials)
-- =============================================================================
create table testimonials (
  id uuid primary key default gen_random_uuid(),
  airtable_record_id text unique,

  testimonial_id text,                        -- Airtable "ID" (single line text, primary field)
  name text,
  content text not null,
  rating text check (rating in ('1', '2', '3', '4', '5')),
  class_type text check (class_type in (
    'Public Classes', 'Private Sessions', 'Corporate Training', 'Community Programs'
  )),
  platform text check (platform in (
    'google', 'yelp', 'facebook', 'trustpilot', 'linkedin', 'nextdoor', 'website', 'survey'
  )),
  review_date date,
  profile_picture jsonb,                      -- Airtable attachment metadata (array of {url, filename, ...})
  platform_screenshot jsonb,
  original_review_url text,
  profile_image_url text,
  is_featured boolean not null default false,
  is_published boolean not null default false,
  status text check (status in ('Active', 'Hidden', 'Archived')) not null default 'Active',
  internal_notes text,
  homepage_position text check (homepage_position in (
    'Quote 1', 'Quote 2', 'Quote 3', 'Quote 4', 'Quote 5', 'Quote 6',
    'None', 'cbo1', 'cbo2', 'corporate1', 'corporate2'
  )),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger testimonials_updated_at before update on testimonials
  for each row execute function set_updated_at();
create index testimonials_is_published_idx on testimonials (is_published);
create index testimonials_is_featured_idx on testimonials (is_featured);
create index testimonials_status_idx on testimonials (status);


-- =============================================================================
-- 8. satisfaction_surveys  (Airtable: Satisfaction Surveys)
-- =============================================================================
create table satisfaction_surveys (
  id uuid primary key default gen_random_uuid(),
  airtable_record_id text unique,

  survey_id bigint not null generated by default as identity unique,
  submission_date timestamptz not null default now(),  -- Airtable formula: CREATED_TIME()
  class_schedule_id uuid references class_schedules(id) on delete set null,
  first_name text,
  last_name text,
  email text,
  phone text,

  q1_overall_experience text check (q1_overall_experience in (
    'Excellent', 'Good', 'Neutral', 'Poor', 'Very Poor'
  )),
  q2_confidence_level text check (q2_confidence_level in (
    'Very Confident', 'Somewhat Confident', 'Neutral',
    'Not Very Confident', 'Not Confident at All'
  )),
  q3_most_valuable_part text,
  q4_areas_for_improvement text,
  q5_would_recommend text check (q5_would_recommend in ('Yes', 'No')),
  q6_opt_in_future_communication text check (q6_opt_in_future_communication in ('Yes', 'No')),
  q7_willing_to_share_experience text check (q7_willing_to_share_experience in (
    'Google/Yelp Review', 'Write Here', 'No', 'Private Feedback'
  )),
  q7_written_testimonial text,
  q7_review_platform_clicked text check (q7_review_platform_clicked in ('Google', 'Yelp', 'Both')),

  preferred_contact_method text[],            -- Airtable multiple select: Phone, Text, Email
  ip_address text,
  user_agent text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger satisfaction_surveys_updated_at before update on satisfaction_surveys
  for each row execute function set_updated_at();
create index satisfaction_surveys_class_schedule_id_idx on satisfaction_surveys (class_schedule_id);
create index satisfaction_surveys_email_idx on satisfaction_surveys (email);


-- =============================================================================
-- 9. form_submissions  (Airtable: Form Submissions)
-- =============================================================================
create table form_submissions (
  id uuid primary key default gen_random_uuid(),
  airtable_record_id text unique,

  submission_id bigint not null generated by default as identity unique,
  first_name text,
  last_name text,
  email text,
  phone text,
  form_type text check (form_type in (
    'Private Training', 'Workplace Safety', 'Community Organizations'
  )),
  submitted_date timestamptz,
  status text check (status in (
    'New', 'Contacted', 'Scheduled', 'Converted', 'Closed'
  )) default 'New',
  newsletter_signup boolean not null default false,
  notes text,
  follow_up_date date,
  web_lead_message text,
  city text,
  state text,
  organization text,
  title text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger form_submissions_updated_at before update on form_submissions
  for each row execute function set_updated_at();
create index form_submissions_status_idx on form_submissions (status);
create index form_submissions_email_idx on form_submissions (email);
create index form_submissions_form_type_idx on form_submissions (form_type);


-- =============================================================================
-- 10. categories  (Airtable: Categories — FAQ categories)
-- =============================================================================
create table categories (
  id uuid primary key default gen_random_uuid(),
  airtable_record_id text unique,

  category_name text not null,
  display_order integer,
  is_active boolean not null default true,
  description text,
  faq_copy text,
  whattoexpect_content_cwc_15plus_copy text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger categories_updated_at before update on categories
  for each row execute function set_updated_at();
create index categories_is_active_idx on categories (is_active);
create index categories_display_order_idx on categories (display_order);


-- =============================================================================
-- 11. faq  (Airtable: FAQ)
-- =============================================================================
create table faq (
  id uuid primary key default gen_random_uuid(),
  airtable_record_id text unique,

  faq_id bigint not null generated by default as identity unique,
  question text not null,
  answer text not null,
  category_id uuid references categories(id) on delete set null,
  question_order integer,
  is_published boolean not null default false,
  categories_copy text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger faq_updated_at before update on faq
  for each row execute function set_updated_at();
create index faq_category_id_idx on faq (category_id);
create index faq_is_published_idx on faq (is_published);


-- =============================================================================
-- 12. waiver_holding_table  (Airtable: Waiver Holding Table)
-- =============================================================================
create table waiver_holding_table (
  id uuid primary key default gen_random_uuid(),
  airtable_record_id text unique,

  name text not null,
  notes text,
  assignee text,                              -- Airtable User (collaborator) — preserved as text for migration
  status text check (status in ('Todo', 'In progress', 'Done')),
  attachments jsonb,
  attachment_summary text,                    -- Airtable AI-generated text
  document_id text,
  first_name text,
  last_name text,
  email text,
  document_name text,
  phone text,
  date_of_birth date,
  street_address text,
  city text,
  state text,
  zip_code text,
  completed_date timestamptz,
  waiver_url text,
  guardian_send_email boolean not null default false,
  guardian_send_sms boolean not null default false,
  is_adult boolean not null default false,
  course_location text,
  emergency_contact_name text,
  emergency_contact_phone text,
  referral_source text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger waiver_holding_table_updated_at before update on waiver_holding_table
  for each row execute function set_updated_at();
create index waiver_holding_table_email_idx on waiver_holding_table (email);
create index waiver_holding_table_status_idx on waiver_holding_table (status);


-- =============================================================================
-- Row-level security
-- =============================================================================
-- RLS is enabled on every table with no policies defined. The Supabase
-- service-role key (used by the /api serverless functions) bypasses RLS, so
-- all current API access continues to work. The anon key has no access —
-- preventing the frontend from hitting Supabase directly. This matches the
-- existing architecture where all reads/writes go through /api.
-- =============================================================================

alter table classes                enable row level security;
alter table class_schedules        enable row level security;
alter table bookings               enable row level security;
alter table participants           enable row level security;
alter table persons                enable row level security;
alter table teaching_assignments   enable row level security;
alter table testimonials           enable row level security;
alter table satisfaction_surveys   enable row level security;
alter table form_submissions       enable row level security;
alter table categories             enable row level security;
alter table faq                    enable row level security;
alter table waiver_holding_table   enable row level security;
